# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Staging
        run:
          git config --local user.email "blainsimpson.bs@gmail.com"
          git config --local user.name "BlaineSimpson"
      - name: Commit and Push to Staging
        run: |
          git add .
          git commit -m "Deploying to staging"
          git push origin staging  # Push the changes to the staging branch

          
  
          
      
