name: .NET CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
       contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal --configuration Release

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy build artifacts
        run: |
          # Publish the application to prepare it for deployment
          dotnet publish -c Release -o ./publish
          rm -rf "./Q3 CICD pipeline"
          cp -r ./publish/* .

      - name: Configure Git
        run: |
          git config --local user.email "blainsimpson.bs@gmail.com"
          git config --local user.name "BlaineSimpson"

      - name: Commit and Push to Staging
        env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
        run: |
               git checkout -b stage || echo "Branch already exists, checking out."
               git add .
               git commit -m "Deploying to stage" || echo "No changes to commit."
               git push origin stage  # Push to the 'stage' branch
