# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test  # Adjust according to your test command
      - name: Run code coverage
        run: npm run coverage  # Adjust according to your coverage command
      - name: Run code analysis
        run: npm run lint  # Adjust according to your linting command

  
deploy:
  runs-on: ubuntu-latest
  needs: build
  environment: staging
     steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Deploy to Staging
        run:
          git config --local user.email "blainsimpson.bs@gmail.com"
          git config --local user.name "BlaineSimpson"
      - name: Copy build artifacts
        run: |
          # Assuming your build artifacts are in the 'bin/Debug/net8.0' directory
          cp -r bin/Debug/net8.0/* .  # Adjust the path as necessary

      - name: Commit and Push to Staging
        run: |
          git add .
          git commit -m "Deploying to staging" || echo "No changes to commit."
          git push origin staging  # Push the changes to the staging branch

          
  
          
      
